services:
  - type: web
    name: cea-dashboard
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FORMSPREE_ENDPOINT
        sync: false
